### ISSUE TITLE
Input/output ordering issues

### ISSUE THREAD

**Issue by GitHunter0** [sa-si-dev/virtual-select#99]
Hey @sa-si-dev , I don't know how to properly communicate the issue here, because I'm not using `virtual-select` directly, I'm using it via [shinyvs](https://github.com/dreamRs/shinyvs), which uses an `R` interface passing the parameters to `virtual-select` as the backend. So I'm sorry about that and I'm hope we can find a way to work around it.

The problem I'm facing is that `virtual-select` seems to force the input/tooltip label/output order to be the same as the one in `value` in `options` . I describe the matter in more details here https://github.com/dreamRs/shinyvs/issues/10 .

Is there a way to make the tooltip labels and the output to follow exactly the order of the input selected? 
I believe that is the standard behavior of other selectInput tools that I use, and it would be great to have an option to obtain that.
`virtual-select` output order actually follows the input order selected later interactively but not the initial selected order passed to `selectedValue`.

Thanks a lot

**Comment by sa-si-dev** [comment]
> Hey @sa-si-dev , I don't know how to properly communicate the issue here, because I'm not using `virtual-select` directly, I'm using it via [shinyvs](https://github.com/dreamRs/shinyvs), which uses an `R` interface passing the parameters to `virtual-select` as the backend. So I'm sorry about that and I'm hope we can find a way to work around it.
> 
> The problem I'm facing is that `virtual-select` seems to force the input/tooltip label/output order to be the same as the one in `value` in `options` . I describe the matter in more details here https://github.com/dreamRs/shinyvs/issues/10 .
> 
> Is there a way to make the tooltip labels and the output to follow exactly the order of the input selected? 
> I believe that is the standard behavior of other selectInput tools that I use, and it would be great to have an option to obtain that.
> `virtual-select` output order actually follows the input order selected later interactively but not the initial selected order passed to `selectedValue`.
> 
> Thanks a lot
> 

@GitHunter0 thanks for letting me know it. I will implement it in the future release.

**Comment by GitHunter0** [comment]
Awesome @sa-si-dev  , I really appreciate your work.

**Comment by sa-si-dev** [comment]
@GitHunter0 I have updated the code to keep the output order would be the same I the user selected order.

This feature is available in the [release v1.0.25](https://github.com/sa-si-dev/virtual-select/releases/tag/v1.0.25)

**Comment by GitHunter0** [comment]
@sa-si-dev , what a great news! This is really important to my current app, I will test it as soon as https://github.com/dreamRs/shinyvs updates it.

**Comment by GitHunter0** [comment]
Hey @sa-si-dev  , I came back to provide some feedback.

First, thanks again for the work.

I did some tests and I'm still having some issues. Here's a MWE using `R`:
```
library(shiny)
library(shinyvs)

ui <- fluidPage(

  shinyvs::virtualSelectInput(
    inputId = "vs_inputs",
    label = NULL,
    choices = data.frame(
        label = c("lab1","lab2","lab3","lab4", "lab5"),
        value = c("val1","val2","val3","val4", "val5")
      ) |> purrr::transpose(),
    selected = c("val2", "val4", "val1"),
    search = TRUE,
    multiple=TRUE,
    popupDropboxBreakpoint = '5000px',
    showValueAsTags = TRUE,
   ),

  verbatimTextOutput("selected_items")
)

server <- function(input, output, session){
  output$selected_items <- renderText({input$vs_inputs})
}

shiny::shinyApp(ui, server)
```

Initial screen: output should be `val2, val4, val1` (in some previous tests it was correct but not anymore for some unknown reason)
![image](https://user-images.githubusercontent.com/26294221/157523872-fe54cf30-1264-49f8-988a-24fb5515820e.png)


After adding `lab3`: now the new input order is respected in the tooltip and output, but not in the `popup`.
![image](https://user-images.githubusercontent.com/26294221/157523906-0ed30610-e996-48f6-bc4e-99448a22b777.png)


Then after closing `lab2` by clicking x in tooltip tag, the tooltip and output change the order, so that `lab3` and `val3` are no longer the last.
![image](https://user-images.githubusercontent.com/26294221/157523942-3184a293-cd02-460f-8023-5d2d0236bf2a.png)


PS: As an aside, `position` parameter is doing nothing in my tests (without popup option), should I open an issue for that?
